USE [master]
GO
/****** Object:  Database [ENREGISTREMENTS]    Script Date: 07/02/2014 11:22:10 ******/
CREATE DATABASE [ENREGISTREMENTS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ENREGISTREMENTS', FILENAME = N'c:\Program Files (x86)\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\ENREGISTREMENTS.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ENREGISTREMENTS_log', FILENAME = N'c:\Program Files (x86)\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\ENREGISTREMENTS_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [ENREGISTREMENTS] SET COMPATIBILITY_LEVEL = 110
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ENREGISTREMENTS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [ENREGISTREMENTS] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ENREGISTREMENTS] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ENREGISTREMENTS] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ENREGISTREMENTS] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ENREGISTREMENTS] SET ARITHABORT OFF 
GO
ALTER DATABASE [ENREGISTREMENTS] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [ENREGISTREMENTS] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [ENREGISTREMENTS] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ENREGISTREMENTS] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ENREGISTREMENTS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ENREGISTREMENTS] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ENREGISTREMENTS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ENREGISTREMENTS] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ENREGISTREMENTS] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ENREGISTREMENTS] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ENREGISTREMENTS] SET  DISABLE_BROKER 
GO
ALTER DATABASE [ENREGISTREMENTS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ENREGISTREMENTS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ENREGISTREMENTS] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [ENREGISTREMENTS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [ENREGISTREMENTS] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ENREGISTREMENTS] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [ENREGISTREMENTS] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [ENREGISTREMENTS] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [ENREGISTREMENTS] SET  MULTI_USER 
GO
ALTER DATABASE [ENREGISTREMENTS] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ENREGISTREMENTS] SET DB_CHAINING OFF 
GO
ALTER DATABASE [ENREGISTREMENTS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [ENREGISTREMENTS] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
USE [ENREGISTREMENTS]
GO
/****** Object:  User [test]    Script Date: 07/02/2014 11:22:10 ******/
CREATE USER [test] FOR LOGIN [benjamin] WITH DEFAULT_SCHEMA=[test]
GO
/****** Object:  Schema [test]    Script Date: 07/02/2014 11:22:10 ******/
CREATE SCHEMA [test]
GO
/****** Object:  Table [dbo].[CMDHOTELS]    Script Date: 07/02/2014 11:22:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[CMDHOTELS](
	[id] [numeric](18, 0) NOT NULL,
	[nom] [varchar](50) NULL,
	[prenom] [varchar](50) NULL,
	[adresse] [varchar](50) NULL,
	[nomHotel] [varchar](50) NULL,
	[date] [date] NULL,
	[duree] [int] NULL,
 CONSTRAINT [PK_CMDHOTELS] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[CMDVOLS]    Script Date: 07/02/2014 11:22:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[CMDVOLS](
	[id] [numeric](18, 0) NOT NULL,
	[nom] [varchar](50) NULL,
	[prenom] [varchar](50) NULL,
	[adresse] [varchar](50) NULL,
	[rib] [varchar](50) NULL,
	[villeDepart] [varchar](50) NULL,
	[villeDestination] [varchar](50) NULL,
	[dateDepart] [date] NULL,
 CONSTRAINT [PK_CMDVOLS] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
USE [master]
GO
ALTER DATABASE [ENREGISTREMENTS] SET  READ_WRITE 
GO
