//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Ce code source a été automatiquement généré par Microsoft.VSDesigner, Version 4.0.30319.18444.
// 
#pragma warning disable 1591

namespace SiteVoyage.WebServiceVol {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service1Soap", Namespace="http://tempuri.org/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getVolsOperationCompleted;
        
        private System.Threading.SendOrPostCallback getInitOperationCompleted;
        
        private System.Threading.SendOrPostCallback getVilleArriveeOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::SiteVoyage.Properties.Settings.Default.SiteVoyage_WebServiceVol_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getVolsCompletedEventHandler getVolsCompleted;
        
        /// <remarks/>
        public event getInitCompletedEventHandler getInitCompleted;
        
        /// <remarks/>
        public event getVilleArriveeCompletedEventHandler getVilleArriveeCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getVols", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getVols(string VilleD, string PaysD, string VilleA, string PaysA, System.DateTime Date) {
            object[] results = this.Invoke("getVols", new object[] {
                        VilleD,
                        PaysD,
                        VilleA,
                        PaysA,
                        Date});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void getVolsAsync(string VilleD, string PaysD, string VilleA, string PaysA, System.DateTime Date) {
            this.getVolsAsync(VilleD, PaysD, VilleA, PaysA, Date, null);
        }
        
        /// <remarks/>
        public void getVolsAsync(string VilleD, string PaysD, string VilleA, string PaysA, System.DateTime Date, object userState) {
            if ((this.getVolsOperationCompleted == null)) {
                this.getVolsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetVolsOperationCompleted);
            }
            this.InvokeAsync("getVols", new object[] {
                        VilleD,
                        PaysD,
                        VilleA,
                        PaysA,
                        Date}, this.getVolsOperationCompleted, userState);
        }
        
        private void OngetVolsOperationCompleted(object arg) {
            if ((this.getVolsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getVolsCompleted(this, new getVolsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getInit", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public departStructure[] getInit() {
            object[] results = this.Invoke("getInit", new object[0]);
            return ((departStructure[])(results[0]));
        }
        
        /// <remarks/>
        public void getInitAsync() {
            this.getInitAsync(null);
        }
        
        /// <remarks/>
        public void getInitAsync(object userState) {
            if ((this.getInitOperationCompleted == null)) {
                this.getInitOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetInitOperationCompleted);
            }
            this.InvokeAsync("getInit", new object[0], this.getInitOperationCompleted, userState);
        }
        
        private void OngetInitOperationCompleted(object arg) {
            if ((this.getInitCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getInitCompleted(this, new getInitCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getVilleArrivee", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public arriveeStructure[] getVilleArrivee(string VilleDepart, string paysDepart) {
            object[] results = this.Invoke("getVilleArrivee", new object[] {
                        VilleDepart,
                        paysDepart});
            return ((arriveeStructure[])(results[0]));
        }
        
        /// <remarks/>
        public void getVilleArriveeAsync(string VilleDepart, string paysDepart) {
            this.getVilleArriveeAsync(VilleDepart, paysDepart, null);
        }
        
        /// <remarks/>
        public void getVilleArriveeAsync(string VilleDepart, string paysDepart, object userState) {
            if ((this.getVilleArriveeOperationCompleted == null)) {
                this.getVilleArriveeOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetVilleArriveeOperationCompleted);
            }
            this.InvokeAsync("getVilleArrivee", new object[] {
                        VilleDepart,
                        paysDepart}, this.getVilleArriveeOperationCompleted, userState);
        }
        
        private void OngetVilleArriveeOperationCompleted(object arg) {
            if ((this.getVilleArriveeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getVilleArriveeCompleted(this, new getVilleArriveeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class departStructure {
        
        private string villeField;
        
        private string paysField;
        
        /// <remarks/>
        public string ville {
            get {
                return this.villeField;
            }
            set {
                this.villeField = value;
            }
        }
        
        /// <remarks/>
        public string pays {
            get {
                return this.paysField;
            }
            set {
                this.paysField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class arriveeStructure {
        
        private string villeField;
        
        private string paysField;
        
        /// <remarks/>
        public string ville {
            get {
                return this.villeField;
            }
            set {
                this.villeField = value;
            }
        }
        
        /// <remarks/>
        public string pays {
            get {
                return this.paysField;
            }
            set {
                this.paysField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getVolsCompletedEventHandler(object sender, getVolsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getVolsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getVolsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getInitCompletedEventHandler(object sender, getInitCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getInitCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getInitCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public departStructure[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((departStructure[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getVilleArriveeCompletedEventHandler(object sender, getVilleArriveeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getVilleArriveeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getVilleArriveeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public arriveeStructure[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((arriveeStructure[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591